### ISSUE TITLE
Tab key does not yield <tab>

### ISSUE THREAD

**Issue by lichray** [lichray/nvi2#15]
From Xin Li:

It looks like the new nvi version don't accept <tab> in the context of
substitute.  A minimal use case would be to replace all leading 8
spaces with tabs, what one would do on older version of nvi would be:

: 1,$ s/^        /<tab>/g

Now, with nvi in FreeBSD 10.x+, entering <tab> won't yield the <tab>
character.  This seems to be a regression from older nvi version.

**Comment by leres** [comment]
I also noticed that tab has changed since the 1.79 BSD version of nvi. For example, if you want to convert all blanks to tabs you might use:

    `:%s/ /^I/g`

With 1.79 you can just type a bare tab. With 2.1.2 (FreeBSD 10.3-RELEASE) or 2.1.3 you must escape ^I with ^V. This makes doing substitution with multiple tabs particularly problematic.

Not only was I a System V vi user in the late 70's but I was one of Keith Bostic's primary testers when he was writing nvi. I trip over this all the time and I think it is definitely a bug.

**Comment by lichray** [comment]
For now, use
```
se filec=
```
in the configuration file to restore the right behavior.  I merely set the default file name completion key to Tab, since the file name completion is greatly improved.  I was thinking about how to make both work without conflicts, but no luck since then.

**Comment by leres** [comment]
Thanks for the workaround: it's super helpful!

Is it safe to say that a future version will remove:
```
 OI(O_FILEC, L("filec=\t"));
```
from opts_init()?

**Comment by lichray** [comment]
Maybe I'll remove it, or someway to let them work together by making completion code contextual.

**Comment by leres** [comment]
I believe  this was solved in 2020 via [f89afc9](https://github.com/lichray/nvi2/commit/f89afc93d7435122dd84f9367aa9ca3ad33ec35b) ("Don't expandtab when we're in command mode").
